name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH deploy to EC2
      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Deploying Node.js app..."
            cd /app
            # Pull latest changes
            git pull || echo "No git repo, skipping pull"
            # Install dependencies
            npm install
            # Restart app with pm2
            pm2 startOrRestart app.js --name "node-app-new"
